name: deploy-py-lambda
on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v6
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: us-east-1

    - name: Zip Lambda function
      run: zip lambda.zip zmanimapi.py

    - name: Upload to S3
      run: aws s3 cp lambda.zip s3://${{ vars.S3_BUCKET_NAME }}/lambda.zip

    - name: Update Lambda function code
      run: aws lambda update-function-code --function-name ZmanimAPI --s3-bucket ${{ vars.S3_BUCKET_NAME }} --s3-key lambda.zip
